version: "3.8"
services:
  mongodb:
    image: mongo:5.0.2
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - 27017:$MONGODB_DOCKER_PORT
    volumes:
      - mongodb:/data/db
  app:
    depends_on:
      - mongodb
    build: ./
    #restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:3000
    environment:
      - DB_HOST=mongodb
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_PORT=$MONGODB_DOCKER_PORT
      - DB_NAME=$DB_NAME
volumes:
  mongodb: